config/routes.rb
Rails.application.routes.draw do
  get "welcome/index"

  root to: 'welcome#index'
  resources :shops
  resources :shops do
    collection { post :import }
  end










end

app/models/shop.rb
class Shop < ActiveRecord::Base
  include PgSearch
  pg_search_scope :search,
  				  :against => [:name, :city],
  				  :using => {
  				  	:tsearch => {:dictionary => "english"}
  				  }  				  

  geocoded_by :address
  after_validation :geocode, :if => :address_changed?
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  
  def search
    @results = Kaminari.paginate_array(PgSearch.multisearch(params[:q]).to_a).page(params[:page] || 1)
  end

end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :set_shop, only: [:show, :edit, :update, :destroy]

  # GET /shops
  # GET /shops.json
  def index
    if params[:search_text].present?
      @shops = Shop.search(params[:search_text])
    else
    @shops = Shop.all
    end
  end

  # GET /shops/1
  # GET /shops/1.json
  def show
  end

  # GET /shops/new
  def new
    @shop = Shop.new
  end

  # GET /shops/1/edit
  def edit
  end

  # POST /shops
  # POST /shops.json
  def create
    @shop = Shop.new(shop_params)

    respond_to do |format|
      if @shop.save
        format.html { redirect_to @shop, notice: 'Shop was successfully created.' }
        format.json { render :show, status: :created, location: @shop }
      else
        format.html { render :new }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shops/1
  # PATCH/PUT /shops/1.json
  def update
    respond_to do |format|
      if @shop.update(shop_params)
        format.html { redirect_to @shop, notice: 'Shop was successfully updated.' }
        format.json { render :show, status: :ok, location: @shop }
      else
        format.html { render :edit }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shops/1
  # DELETE /shops/1.json
  def destroy
    @shop.destroy
    respond_to do |format|
      format.html { redirect_to shops_url, notice: 'Shop was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shop
      @shop = Shop.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shop_params
      params.require(:shop).permit(:chain, :name, :latitude, :longitude, :address, :city, :zip, :phone, :country_code)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shop Your City</title>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js" type="text/javascript"></script>  
    <script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>

    <meta name='viewport' content='initial-scale=1,maximum-scale=1,user-scalable=no' />
    <link rel="stylesheet" href="http://cdn.leafletjs.com/leaflet-0.7.3/leaflet.css" />
    <script src="http://cdn.leafletjs.com/leaflet-0.7.3/leaflet.js"></script>
    <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/1.5.2/css/ionicons.min.css">
    <link rel="stylesheet" href="css/leaflet.awesome-markers.css">
    <script src="js/leaflet.awesome-markers.js"></script>

    <link href='http://fonts.googleapis.com/css?family=Oswald' rel='stylesheet' type='text/css'>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_include_tag 'vendor/modernizr' %>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
  </head>
  <body>
<nav class="top-bar" data-topbar role="navigation">
  <ul class="title-area">
    <li class="name">
      <h1><a href="#">Shopmiums spots in Your City</a></h1>
    </li>
    <li class="toggle-topbar menu-icon"><a href="#"><span>Shops</span></a></li>
  </ul>

  <section class="top-bar-section">
    <ul class="right">
      <li class="active"><%= link_to '+', new_shop_path %></li>
      <li class="has-dropdown">
        <a href="#">Shops</a>
        <ul class="dropdown">
          <li><%= link_to 'Add a Shop', new_shop_path %></li>
          <li class="active"><%= link_to 'Shops List', shops_path %></li>
        </ul>
      </li>
    </ul>
  </section>
</nav>
    <%= yield %>
  </body>
</html>

app/views/shops/_form.html.erb
<%= form_for(@shop) do |f| %>
  <% if @shop.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@shop.errors.count, "error") %> prohibited this shop from being saved:</h2>

      <ul>
      <% @shop.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :chain %><br>
    <%= f.text_field :chain %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :zip %><br>
    <%= f.text_field :zip %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :country_code %><br>
    <%= f.text_field :country_code %>
  </div>
  <div class="actions", style="text-align :center">
    <%= f.submit :style => "width:15%;height:5%;background-color:#ff1493;color:white;padding:10px", :class => "button" %>
  </div>
<% end %>

app/views/shops/delete.html.haml
%h1 Products#delete
%p Find me in app/views/products/delete.html.haml

app/views/shops/edit.html.erb
<h1 style="text-align :center">Editing Shop</h1>

<%= render 'form' %>

<%= link_to 'Show', @shop %> |
<%= link_to 'Back', shops_path %>

app/views/shops/index.html.erb
<p id="notice"><%= notice %></p>

<h1 style="text-align :center">Listing Shops</h1>

<div style="text-align :center">
<%= form_tag shops_path, method: :get do%>
<%= text_field_tag(:search_text, nil, :style => "width:30%;margin: auto;margin-bottom:10px;") %>
<%= submit_tag "Search", :style => "width:15%;height:5%;background-color:#ff1493;color:white;padding:10px"%>
<% end %>
</div>

<table class="table1", style="width:1200px">
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>City</th>
      <th>Zip</th>
    </tr>
  </thead>
  <tbody>
    <% @shops.each do |shop| %>
      <tr>
  	  	<td><%= shop.name %></td>
      	<td><%= shop.address %></td>
      	<td><%= shop.city %></td>
      	<td style="text-align:right;"><%= shop.zip %></td>
      	<td style="text-align:right;"><%= link_to 'Show', shop %></td>
      	<td style="text-align:right;"><%= link_to 'Edit', edit_shop_path(shop) %></td>
        <td style="text-align:right;"><%= link_to 'Destroy', shop, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

app/views/shops/new.html.erb
<h1 style="text-align :center">New Shop</h1>

<%= render 'form' %>

app/views/shops/show.html.erb
<p id="notice"><%= notice %></p>

<br>
<div style="text-align :center">
<%= form_tag shops_path, method: :get do%>
<%= text_field_tag(:search_text, nil, :style => "width:30%;margin: auto;margin-bottom:10px;") %>
<%= submit_tag "Search", :style => "width:15%;height:5%;background-color:#ff1493;color:white;padding:10px"%>
<% end %>
</div>

<table style="width:1200px">
  <thead>
    <tr>
      <th>Chain</th>
      <th>Name</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>Address</th>
      <th>City</th>
      <th>Zip</th>
      <th>Phone</th>
      <th>Country Code</th>
  </tr>
  </thead>
  <tbody>
  <tr>
    <td><%= @shop.chain %></td>
    <td><%= @shop.name %></td>
    <td><%= @shop.latitude %></td>
    <td><%= @shop.longitude %></td>
    <td><%= @shop.address %></td>
    <td><%= @shop.city %></td>
    <td><%= @shop.zip %></td>
    <td><%= @shop.phone %></td>
    <td><%= @shop.country_code %></td>
    <td><%= link_to 'Edit', edit_shop_path(@shop) %></td>
    <td><%= link_to 'Destroy', @shop, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  </tbody>
</table>

<br>
<hr>
</hr>
<br>

<div class="nearby">
    <h3>Nearbys Shops</h3>
  <ul>
    <% for shop in @shop.nearbys(10) %>
       <li><%= link_to shop.name, shop %> (<%= shop.distance.round(2) %> miles)</li>
    <% end %>
  </ul>
</div>
<br>

app/views/welcome/index.html.erb
<br>
<br>
<h1 style="font-family: 'Open Sans', sans-serif;text-align:center;">Welcome dears customers here you can find the bests plans of your city!</h1>
<br>


<div class="row">
  <div class="large-12 text-center columns">
	<ul class="stack-for-small round secondary button-group fix_button_group">
	  <li><a href="shops/new" class="button", style="background-color:#000000">Add a new shop</a></li>
	  <li><a href="shops" class="button", style="background-color:#ff1493">Shops List</a></li>
	</ul>
  </div>
</div>